[package]
name = "bd_data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bd_core = { path = "../bd_core" }

bevy_app.workspace = true

serde.workspace = true
ron.workspace = true
thiserror.workspace = true
tracing.workspace = true
