[package]
name = "bd_test_support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bd_core = { path = "../bd_core" }
bd_data = { path = "../bd_data" }

bevy.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true

insta.workspace = true
rand.workspace = true
rand_chacha.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
